name: pato_track
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  intl: ^0.20.2
  provider: ^6.1.2
  path: ^1.9.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^7.2.0
  fluttertoast: ^9.0.0
  google_fonts: ^8.0.2
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  flutter_secure_storage: ^10.0.0
  flutter_local_notifications: ^21.0.0-dev.2
  flutter_sms_inbox: ^1.0.3
  timezone: ^0.11.0
  permission_handler: ^12.0.1
  url_launcher: ^6.3.0
  
  cloud_firestore: ^6.1.2
  fl_chart: ^1.1.1
  pdf: ^3.10.8
  printing: ^5.12.0
  http: ^1.2.1
  cached_network_image: ^3.4.1

  # NEW: Package for creating a secure upload signature
  crypto: ^3.0.3
  lucide_icons_flutter: ^3.1.10

  # Tier 1 Dependencies
  google_mlkit_text_recognition: ^0.13.0
  decimal: ^2.3.3
  image: ^4.3.0
  flutter_dotenv: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/mpesa_logo.png
    - assets/google_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
