// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyTw1WzZgJ9rxHYjtsJAbKcnT0zofgRaY',
    appId: '1:474420702424:web:f673c697460c648e1cc2a4',
    messagingSenderId: '474420702424',
    projectId: 'patotrack',
    authDomain: 'patotrack.firebaseapp.com',
    storageBucket: 'patotrack.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyTw1WzZgJ9rxHYjtsJAbKcnT0zofgRaY',
    appId: '1:474420702424:android:4d3ed2ba7220beee0ebbad',
    messagingSenderId: '474420702424',
    projectId: 'patotrack',
    storageBucket: 'patotrack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEo4DiwXoxcnCz6EVRTAqa-AKagGbGIKM',
    appId: '1:474420702424:ios:49b415f43a174f6b0ebbad',
    messagingSenderId: '474420702424',
    projectId: 'patotrack',
    storageBucket: 'patotrack.firebasestorage.app',
    iosBundleId: 'com.patotrack.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEo4DiwXoxcnCz6EVRTAqa-AKagGbGIKM',
    appId: '1:474420702424:ios:49b415f43a174f6b0ebbad',
    messagingSenderId: '474420702424',
    projectId: 'patotrack',
    storageBucket: 'patotrack.firebasestorage.app',
    iosBundleId: 'com.patotrack.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyTw1WzZgJ9rxHYjtsJAbKcnT0zofgRaY',
    appId: '1:474420702424:web:3938766407cc881c1cc2a4',
    messagingSenderId: '474420702424',
    projectId: 'patotrack',
    authDomain: 'patotrack.firebaseapp.com',
    storageBucket: 'patotrack.firebasestorage.app',
  );
}
